# Generated by Django 3.0.2 on 2020-01-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentries',
            name='entry_text',
            field=models.TextField(max_length=500),
        ),
    ]
